### ISSUE TITLE
甚至不需要用python环境，有个终端基本就能执行

### ISSUE THREAD

**Issue by Ruiyuan-Zhang** [yep96/ZJU_healthreport#2]
![image](https://user-images.githubusercontent.com/71813586/146666356-1a58bd43-ddfd-4b87-b223-5330d5e862d8.png)

**Comment by yep96** [comment]
每次post的表单里created是跟着时间变化的，后来还加进了别的验证，而且我主要的目的是更新每次变化的cookies。当然curl配合grep/sed等也可以，不过python更方便罢了。
